### PR TITLE
Remove some patches.

### PR DESCRIPTION
**Pull request by decko**

### CODE REVIEW

**Review by dkliban — APPROVED** [review]

**Review by mikedep333 — APPROVED** [review]
🩹

**Review by mikedep333 — CHANGES_REQUESTED** [review]
As dkliban explained, the ostree test failed. So patch is still needed.

**Comment by decko** [comment]
Thanks @mikedep333. I've added the patch back.

**Review by mikedep333 — APPROVED** [review]

**Comment by mikedep333** [comment]
Merging, I'd like to test the new Konflux ReleasePlanAdmission.

**Pull request merged**
